const projects = [
  {
    name: "Grace for the Race",
    id: "project1",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    imageLight: "../images/designs/grace-race-WHITE.png",
    imageDark: "../images/designs/grace-race-BLACK.png",
    type: "shirt",
  },
  {
    name: "C&C Window Tint",
    id: "project2",
    description: "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    imageLight: "../images/designs/c&c-tint-WHITE.png",
    imageDark: "../images/designs/c&c-tint-BLACK.png",
    type: "shirt",
  },
  {
    name: "Cut",
    id: "project3",
    description: "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.",
    imageLight: "../images/designs/cut-WHITE.png",
    imageDark: "../images/designs/cut-BLACK.png",
    type: "shirt",
  },
  {
    name: "Equality",
    id: "project4",
    description: "Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt.",
    imageLight: "../images/designs/equal-WHITE.png",
    imageDark: "../images/designs/equal-BLACK.png",
    type: "shirt",
  },
  {
    name: "Fast Freddies Greenscapes",
    id: "project5",
    description: "Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem.",
    imageLight: "../images/designs/fast-freddies-WHITE.png",
    imageDark: "../images/designs/fast-freddies-BLACK.png",
    type: "shirt",
  },
  {
    name: "Jay Quick Tire Shop",
    id: "project6",
    description: "Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur?",
    imageLight: "../images/designs/jay-quick-WHITE.png",
    imageDark: "../images/designs/jay-quick-BLACK.png",
    type: "shirt",
  },
  {
    name: "Love Creatively",
    id: "project7",
    description: "Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur?",
    imageLight: "../images/designs/love-creatively-WHITE.png",
    imageDark: "../images/designs/love-creatively-BLACK.png",
    type: "shirt",
  },
  {
    name: "Sharing Love",
    id: "project8",
    description: "Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur?",
    imageLight: "../images/designs/love-god-WHITE.png",
    imageDark: "../images/designs/love-god-BLACK.png",
    type: "shirt",
  },
  {
    name: "All About the Ambiance",
    id: "project9",
    description: "Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur?",
    imageLight: "../images/designs/mz-c-bnb-WHITE.png",
    imageDark: "../images/designs/mz-c-bnb-BLACK.png",
    type: "shirt",
  },
  {
    name: "Perotte's Enterprises",
    id: "project10",
    description: "Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur?",
    imageLight: "../images/designs/perottes-WHITE.png",
    imageDark: "../images/designs/perottes-BLACK.png",
    type: "shirt",
  },
  {
    name: "Ray's Lawn Service",
    id: "project11",
    description: "Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur?",
    imageLight: "../images/designs/ray-lawn-WHITE.png",
    imageDark: "../images/designs/ray-lawn-BLACK.png",
    type: "shirt",
  },
  {
    name: "Stay With My Son",
    id: "project12",
    description: "Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur?",
    imageLight: "../images/designs/stay-with-son-WHITE.png",
    imageDark: "../images/designs/stay-with-son-BLACK.png",
    type: "shirt",
  },
  {
    name: "Swarm Team Reunion Cruise",
    id: "project13",
    description: "Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur?",
    imageLight: "../images/designs/swarm-team-WHITE.png",
    imageDark: "../images/designs/swarm-team-BLACK.png",
    type: "shirt",
  },
  {
    name: "Turned 20 Twice",
    id: "project14",
    description: "Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur?",
    imageLight: "../images/designs/turned-20-WHITE.png",
    imageDark: "../images/designs/turned-20-BLACK.png",
    type: "shirt",
  },
  {
    name: "God Says I Am",
    id: "project15",
    description: "Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur?",
    imageLight: "../images/designs/sample_15.jpg",
    imageDark: "../images/designs/sample_15.jpg",
    type: "shirt",
  },
  {
    name: "WDI Landscaping",
    id: "project16",
    description: "Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur?",
    imageLight: "../images/designs/wdi-WHITE.png",
    imageDark: "../images/designs/wdi-BLACK.png",
    type: "shirt",
  },
  {
    name: "project 17",
    id: "project17",
    description: "Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur?",
    imageLight: "../images/designs/sample_17.jpg",
    imageDark: "../images/designs/sample_17.jpg",
    type: "shirt",
  },
  {
    name: "When You Can't Do What You Want",
    id: "project18",
    description: "Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur?",
    imageLight: "../images/designs/when-you-cant-WHITE.png",
    imageDark: "../images/designs/when-you-cant-BLACK.png",
    type: "shirt",
  },
]

export default projects
